# outdated
version: "3.8"
services:
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  noa:
    image: backend223
    container_name: backend
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy
 