on:
  push

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World!"
  pass-secret-to-action:
    runs-on: ubnutu-latest
    steps:
      - name: Use repo secret
        run: echo ${{ secrets.MY_SECRET }}

